### ISSUE TITLE
您好，我用你这个源码编译的RM2100为什么会卡死啊？

### ISSUE THREAD

**Issue by haoxinyu1** [vipshmily/Padavan-build1#1]
您好，我用你这个源码编译的RM2100为什么会卡死啊？能不能帮忙编译一版，你的这个ss很好用

**Comment by vipshmily** [comment]
你只是fork我云编译的码而已，这跟你实际编译出来的固件使用卡不卡是没任何关系的，能影响和决定编译出来的固件的，就只跟你拉取用来编译固件的源码有关

**Comment by haoxinyu1** [comment]
编译源码也是用的你的[Padavan-KVR](https://github.com/vipshmily/Padavan-KVR)，只是你的源码那里不能提交lssues，所以就在这里提问了
