### ISSUE TITLE
访问国内网站特别慢有的打不开是怎么回事啊？

### ISSUE THREAD

**Issue by haoxinyu1** [vipshmily/Padavan-build1#2]
路由器RM2100，编译的您源码
https://github.com/vipshmily/Padavan-3.4-KVR.git
路由是PPPOE拨号，然后就是访问国内网站特别慢，大部分打不开，如百度云盘测速网啥的都打不开，但是科学上网非常好用，所以想用这套源码编译，我也用您编译的
[RM2100 MI-R4A K2P_2023.03.31-2003](https://github.com/vipshmily/Padavan-build/releases/tag/v2023.03.31-2003)
这一版测试了，一样的情况，是设置不对还是哪里的问题呢？

**Comment by vipshmily** [comment]
这个问题我也知道，但暂时还不知道是什么原因？我用vb1980的源码编译出来也是一样的问题存在，你光猫改一下不要桥接，然后更换成IPoEd动态IP应该就没问题了，网速其实和PPPOE差不了什么的

**Comment by vipshmily** [comment]
你可以编译4.4试试看怎样？会不会出现同样的问题

**Comment by haoxinyu1** [comment]
改为光猫拨号确实没有那个问题了，您可以试试
https://github.com/keke1023/Padavan.git
这个源码，他这个编译出来的PPPOE是没有问题的，只是科学上网没有您的好用

**Comment by vipshmily** [comment]
你现在用的是哪个运营商的宽带？你试过用https://github.com/keke1023/Padavan.git这个源码确定是不会出现那种问题吗？我现在都有点怀疑会不会是运营商宽带拨号的问题或拨号设置的问题，但不敢确定

**Comment by haoxinyu1** [comment]
联通的宽带，确定https://github.com/keke1023/Padavan.git  没有那个问题，因为在使用您这个之前我就是用的keke的，拨号是没有问题的

**Comment by vipshmily** [comment]
你同步或fork我的https://github.com/vipshmily/Padavan.git   我今天做了比较大的更新，增加完善了其他插件功能，你编译试试PPPOE拨号还会不会存在原来那个问题

**Comment by haoxinyu1** [comment]
今天试了下，https://github.com/vipshmily/Padavan.git  用这个打包后，PPPOE拨号还是那样，然后我对比了你的和keke的文件，把linux-3.4.x里面的文件还原后在打包刷好PPPOE拨号就没问题了，我不知道这样会不会发生错误，目前路由器运行是正常的

**Comment by vipshmily** [comment]
应该是你发现的原因导致的PPPOE拨号有问题，我一直都忽略了，既然你还原了，你直接推过来给我，我合并一下
